### ISSUE TITLE
Missing from Community Mods menu in-game

### ISSUE THREAD

**Issue by mrbfrank** [carn1x/pa-4k-gui-scale#1]
Hi, I'd like to try this mod but it does not appear listed in the Community Mods menu. See this link which shows an error: https://palobby.com/community-mods/

Error: missing uber forums link

**Comment by carn1x** [comment]
I believe the mod was disabled by a community member "higher up" for being obsolete now that similar functionality was added to the core game. I haven't verified that this is the case, but I trust them enough that I haven't checked :)
